name: 'feature 이슈 생성'
description: '새로운 기능 추가'
labels: [👍feature👍]
title: '[feature] 이슈 제목을 입력해주세요(명사형)'
body:
  - type: input
    id: dueDate
    attributes:
      label: '🗓️ 마감일 🗓️'
      placeholder: '2025-09-20'
    validations:
      required: false

  - type: dropdown
    id: assignee
    attributes:
      label: '담당자(Assignee)'
      options:
        - alsdddk
        - k-dhyun
        - leesumang
        - neve1n
    validations:
      required: true
      
  - type: input
    id: description
    attributes:
      label: '📝 상세 내용(Description) 📝'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: false

  - type: textarea
    id: tasks
    attributes:
      label: '✅ 체크리스트(Tasks)'
      description: '해당 이슈에 대해 필요한 작업목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true
