import {
  StyleSheet,
  Dimensions
} from 'react-native'

import {
  CHECKBOX_SIZE,
  SCHEDULE_BOX_HEIGHT,
  TASK_BOX_HEIGHT,
  EVENT_AREA_PADDING_TOP,
  ITEM_MARGIN_VERTICAL,
  SINGLE_SCHEDULE_BORDER_WIDTH,
  TEXT_HORIZONTAL_PADDING,
  EVENT_HPAD,
  DARK_GRAY_COLOR,
  SCHEDULE_COLOR,
  SCHEDULE_LIGHT_COLOR
} from './constants'

const { width: screenWidth } = Dimensions.get('window')
const horizontalPadding = 12
export const cellWidth = (screenWidth - horizontalPadding) / 7
const MIN_CELL_HEIGHT = 115

export const S = StyleSheet.create({
  contentContainerWrapper: { flex: 1, paddingBottom: 0, paddingTop: 0 },
  contentArea: { flex: 1, paddingHorizontal: 6, paddingTop: 5 },
  scrollContentContainer: { paddingBottom: 20 },
  dayHeader: {
    flexDirection: 'row',
    marginBottom: 5,
    marginTop: 2,
    paddingHorizontal: 6,
  },
  dayCellFixed: { width: cellWidth, alignItems: 'center' },
  dayTextBase: { textAlign: 'center', color: '#333', fontWeight: '600', fontSize: 15 },
  sunText: { color: 'red' },
  satText: { color: '#000000' },

  calendarGrid: {},
  weekRow: {
    flexDirection: 'row',
    width: '100%',
  },
  dateCell: {
    width: cellWidth,
    minHeight: MIN_CELL_HEIGHT,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    position: 'relative',
    borderWidth: 0,
    paddingBottom: 2,
    overflow: 'visible',
    zIndex: 1,
  },
  dateNumberWrapper: {
    height: 18,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingLeft: 6,
    paddingTop: 0,
    position: 'relative',
  },
  eventArea: {
    width: '100%',
    paddingHorizontal: EVENT_HPAD,
    paddingTop: EVENT_AREA_PADDING_TOP,
    paddingBottom: ITEM_MARGIN_VERTICAL,
  },
  focusedDayBorder: { borderWidth: 0.8, borderColor: '#AAAAAA', borderRadius: 4 },
  todayBorder: { borderWidth: 1.5, borderColor: '#CCCCCC', borderRadius: 4 },
  dateNumberBase: { color: 'black', zIndex: 1 },

  ringBase: {
    position: 'absolute',
    top: 1,
    left: 1,
    right: 1,
    bottom: 1,
    borderRadius: 6,
    pointerEvents: 'none',
    zIndex: 3,
  },
  focusRing: { borderWidth: 0.8, borderColor: '#AAAAAA' },
  todayRing: { borderWidth: 1.0, borderColor: '#CCCCCC', zIndex: 0 },

  sunDate: { color: 'red' },
  satDate: { color: '#000000' },
  otherMonthDateText: { color: 'gray' },
  otherMonthSunDate: { color: '#F0A0A0' },
  otherMonthSatDate: { color: '#A0A0FF' },
  otherMonthHolidayText: { color: '#F08080' },

  todayDateText: { fontWeight: 'bold' },
  holidayDateText: { color: 'red' },
  todayRoundedSquare: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 4,
    top: 1,
    left: 3,
    backgroundColor: 'rgba(176, 79, 255, 0.15)',
    zIndex: 1,
  },
  holidayText: {
    position: 'absolute',
    right: 6,
    top: 3,
    fontSize: 8,
    color: 'red',
    lineHeight: 14,
    fontWeight: 'normal',
  },
  smallHolidayText: { fontSize: 7 },
  scheduleBox: {
    height: SCHEDULE_BOX_HEIGHT,
    borderRadius: 3,
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingHorizontal: 0,
    marginBottom: ITEM_MARGIN_VERTICAL,
    overflow: 'hidden',
  },
  recurringSchedule: {
    backgroundColor: SCHEDULE_COLOR,
    paddingLeft: TEXT_HORIZONTAL_PADDING,
    paddingRight: TEXT_HORIZONTAL_PADDING,
  },
  singleSchedule: {
    backgroundColor: SCHEDULE_LIGHT_COLOR,
    paddingLeft: TEXT_HORIZONTAL_PADDING,
    paddingRight: TEXT_HORIZONTAL_PADDING,
  },
  singleDaySolid: {
    backgroundColor: SCHEDULE_COLOR,
    paddingLeft: TEXT_HORIZONTAL_PADDING,
    paddingRight: TEXT_HORIZONTAL_PADDING,
  },
  singleDayTextWhite: { color: '#FFF', fontWeight: '700', marginTop: -1 },
  singleScheduleBorder: {
    borderLeftWidth: SINGLE_SCHEDULE_BORDER_WIDTH,
    borderRightWidth: SINGLE_SCHEDULE_BORDER_WIDTH,
    borderColor: SCHEDULE_COLOR,
  },
  scheduleText: {
    fontSize: 10.5,
    fontWeight: '600',
    textAlign: 'left',
    lineHeight: SCHEDULE_BOX_HEIGHT,
  },
  recurringScheduleText: {
    color: '#FFFFFF',
    marginTop: 0.5,
    fontWeight: '700',
    paddingLeft: 4,
  },
  singleScheduleText: { color: '#000', marginTop: -1 },
  endTodayCap: {
    position: 'absolute',
    right: -3,
    top: (SCHEDULE_BOX_HEIGHT - 8) / 2,
    width: 6,
    height: 8,
    borderRadius: 4,
  },

  checkboxTouchArea: { marginRight: 3, alignSelf: 'center' },
  checkboxBase: {
    width: CHECKBOX_SIZE,
    height: CHECKBOX_SIZE,
    borderRadius: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  checkboxOff: { backgroundColor: '#FFFFFF', borderColor: '#000000' },
  checkboxOn: { backgroundColor: DARK_GRAY_COLOR, borderColor: DARK_GRAY_COLOR },
  checkMark: {
    color: '#FFFFFF',
    fontSize: 7,
    fontWeight: '900',
    lineHeight: CHECKBOX_SIZE,
  },
  taskBox: {
    height: TASK_BOX_HEIGHT,
    backgroundColor: 'transparent',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: '#000000',
    paddingLeft: 1,
    paddingRight: 0,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: ITEM_MARGIN_VERTICAL,
  },
  taskBoxNoCheckbox: {
    height: TASK_BOX_HEIGHT,
    backgroundColor: 'transparent',
    borderRadius: 2,
    paddingLeft: 1,
    paddingRight: 0,
    justifyContent: 'center',
    marginBottom: ITEM_MARGIN_VERTICAL,
  },
  taskBoxBordered: {
    borderWidth: 1,
    borderColor: '#000000',
    backgroundColor: '#FFFFFF',
    paddingLeft: 2,
    paddingRight: TEXT_HORIZONTAL_PADDING,
  },
  taskText: {
    fontSize: 12,
    color: '#333',
    fontWeight: '500',
    flex: 1,
    textAlign: 'left',
    lineHeight: TASK_BOX_HEIGHT,
    textAlignVertical: 'center',
  },

  dimmedItem: {
    opacity: 0.3,
  },

  multiDayContainer: {
    width: '100%',
    marginBottom: ITEM_MARGIN_VERTICAL,
    height: SCHEDULE_BOX_HEIGHT,
    justifyContent: 'center',
    overflow: 'visible',
    position: 'relative',
  },
  multiBarBase: {
    height: SCHEDULE_BOX_HEIGHT,
    backgroundColor: SCHEDULE_LIGHT_COLOR,
    paddingHorizontal: 0,
    justifyContent: 'center',
    borderRadius: 0,
    borderTopWidth: 0,
    borderBottomWidth: 0,
    borderColor: 'transparent',
  },
  multiBarLeftEdge: {
    borderLeftWidth: SINGLE_SCHEDULE_BORDER_WIDTH,
    borderColor: SCHEDULE_COLOR,
    borderTopLeftRadius: 3,
    borderBottomLeftRadius: 3,
    paddingLeft: TEXT_HORIZONTAL_PADDING,
  },
  multiBarRightEdge: {
    borderRightWidth: SINGLE_SCHEDULE_BORDER_WIDTH,
    borderColor: SCHEDULE_COLOR,
    borderTopRightRadius: 3,
    borderBottomRightRadius: 3,
    paddingRight: TEXT_HORIZONTAL_PADDING,
  },
  multiBarText: {
    fontSize: 12,
    color: '#000',
    fontWeight: '600',
    lineHeight: SCHEDULE_BOX_HEIGHT,
  },
  multiStartContainer: {},
  multiEndContainer: {},
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.35)',
    zIndex: 99,
  },

  laneSpacer: {
    height: SCHEDULE_BOX_HEIGHT,
    marginBottom: ITEM_MARGIN_VERTICAL,
  },

  laneRow: { marginBottom: ITEM_MARGIN_VERTICAL },
  laneRowLast: { marginBottom: 0 },

  multiSegAbs: {
    position: 'absolute',
    left: -EVENT_HPAD,
    top: 0,
    height: SCHEDULE_BOX_HEIGHT,
    justifyContent: 'center',
    zIndex: 10,
  },
})